version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3

  - package-ecosystem: docker
    directory: /chipsec_tools/log_parser
    schedule:
      interval: daily
    cooldown:
      default-days: 3

  - package-ecosystem: pip
    directory: /chipsec_tools/log_parser
    schedule:
      interval: daily
    cooldown:
      default-days: 3
